### ISSUE TITLE
Need more guide about how to use it after installation

### ISSUE THREAD

**Issue by fengyedou** [lkdjiin/coco#43]
After coco installation, how to test our code coverage? I donot understand much about the detail steps, can you guide how to move on after installation, I only see require 'coco' in the documentation, but no other steps. Can you give a more detailed step lists of how to test the codes and get the coverage report? If there is an example, that will be fine.

Thanks.

**Comment by lkdjiin** [comment]
There is **no other steps** required in order to build a basic report! Just run your test as always (you have a test suite, do you?) and either **i)** See the result on console output or **ii)** look at `coverage/index.html`.

Does this help?
