### ISSUE TITLE
coco running on rubocop when raking.

### ISSUE THREAD

**Issue by josephbridgwaterrowe** [lkdjiin/coco#53]
coco is running over rubocop when called using rake.

For example:

``` bash
COCO=1 rake rubocop

Inspecting 139 files
...........................................................................................................................................

139 files inspected, no offenses detected
Cover 4% | 28 uncovered | 31 files
```

``` ruby
# Rakefile
require File.expand_path('../config/application', __FILE__)
require 'rubocop/rake_task'

Rails.application.load_tasks
RuboCop::RakeTask.new

task :eslint do
  system('node_modules/.bin/eslint app/assets/javascripts') or exit 1
end

task :scss_lint do
  system('scss-lint app/assets/stylesheets') or exit 1
end

task default: %w(spec rubocop eslint scss_lint)
```

When running rubocop on its own however, this does not occur:

``` bash
COCO=1 rubocop

Inspecting 139 files
...........................................................................................................................................

139 files inspected, no offenses detected
```

And here is the `.coco.yml` file:

``` yaml
# .coco.yml
:always_run: false
:exclude:
- config/initializers
:include:
- app
- lib
:show_link_in_terminal: true
```

**Comment by lkdjiin** [comment]
Hello @josephbridgwaterrowe 

I don't know rubocop a lot. It should not trigger the tests, right?

Do you have this same output :

    Cover 4% | 28 uncovered | 31 files

…when you run coco directly with rspec (`COCO=1 rspec`) ?

**Comment by josephbridgwaterrowe** [comment]
Hi @lkdjiin 

Thanks for your response, I would not expect rubocop to trigger the tests, but I wonder if it is doing something todo with `Coverage`... I can take a deeper look today.

When running `COCO=1 rspec` I __do not__ see the output:

```
Cover 4% | 28 uncovered | 31 files
```

I see the output that I would expect.

**Comment by lkdjiin** [comment]
By *«the output that I would expect»* do you mean that you are seeing other numbers? (the good ones?)
Does this mean that `Cover 4% | 28 uncovered | 31 files` are not the metrics of your project?

**Comment by josephbridgwaterrowe** [comment]
Yes, our projects metrics are output as:

```
Cover 99% | 0 uncovered | 81 files
```

When running `COOC=1 rspec`

Sorry for the confusion.

**Comment by josephbridgwaterrowe** [comment]
@lkdjiin 

Further findings, `COCO=1 rubocop` does not generate the coverage output, so it would seem to be a combination of `rake` and `rubocop`.

**Comment by lkdjiin** [comment]
By the way congrats for the 99% ;)

What does your `rake spec` do? Is it a custom one? What is your version of rails & ruby?

I think I'll have to try it locally on my computer to understand what's going on…

Could you please paste your gemfile and the head of your spec_helper ? (just to be sure)

**Comment by josephbridgwaterrowe** [comment]
Thanks, although the project is still in its infancy :smile:

I'm believe that that `rake spec` is the default `RSpec` behavior.

Ruby 2.3.0
Rails 4.2.6

```ruby
# Gemfile
source 'https://rubygems.org'

ruby '2.3.0'

gem 'aws-sdk', '~> 2'
gem 'bourbon'
gem 'browserify-rails'
gem 'classy_enum', '4.0.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise'
gem 'draper'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jsonapi-resources'
gem 'livingstyleguide'
gem 'money-rails'
gem 'neat'
gem 'non-stupid-digest-assets'
gem 'pg'
gem 'puma'
gem 'rails', '4.2.6'
gem 'rails_12factor', group: :production
gem 'rubocop', require: false
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'simple_form', '3.2.1'
gem 'slim'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'bitters'
  gem 'coco'
  gem 'flay'
  gem 'flog'
  gem 'refills'
  gem 'scss_lint', require: false
  gem 'web-console', '~> 2.0'
end

group :development, :test do
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'rspec-rails', '~> 3.0'
end

group :test do
  gem 'capybara'
  gem 'codeclimate-test-reporter', require: nil
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'poltergeist'
  gem 'shoulda-matchers'
end
```

```ruby
# spec/spec_helper.rb
if ENV['CODECLIMATE_REPO_TOKEN']
  require 'codeclimate-test-reporter'

  CodeClimate::TestReporter.start
else
  require 'coco'
end

RSpec.configure do |config|
  config.order = :random

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
    expectations.syntax = :expect
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
end
```

**Comment by lkdjiin** [comment]
Hi @josephbridgwaterrowe 
I haven't found the time yet to reproduce your issue locally, and I don't know if it still occurs.

One idea by the way: 
* remove coco from the group `:development` in your gemfile
* add it with `gem 'coco', require: false` in the group `:test`

**Comment by josephbridgwaterrowe** [comment]
Hi @lkdjiin 

Thanks for the follow up, I'll give that a go... although I imagine if we did that then we wouldn't be able to use `COCO=1` when running `rake`.

**Comment by lkdjiin** [comment]
No news is good news
