### ISSUE TITLE
Coverage % could be more precise

### ISSUE THREAD

**Issue by TiteiKo** [lkdjiin/coco#54]
On large projects, 1% of coverage can represent a lot of lines/files.

Having a float (ex: 73.34%) instead of an int (73%) for the global coverage would be really useful to see the coverage impact of a commit/branch/other

**Comment by lkdjiin** [comment]
Hello @TiteiKo 

A decimal format for the global rate is a very good idea :+1: 

Let me know if you would like to implement it :wink:

**Comment by TiteiKo** [comment]
I'm on it, just one question... do you think it should be configurable via an option?

As most people use it on their CI with parsers to get the coverage, breaking the format wouldn't be very nice...

So I was thinking an option (cover_rounding?) by default at 0, but I'm currently fighting against the Configuration that needs to be passed on to the Summary.... And now it's a mess... I'm almost thinking of making the Configuration available from anywhere..

**Comment by lkdjiin** [comment]
Just be simple, please ;) I think you're right that `73.34` is better than `73`. 
So we should use `73.34` as the default, isn't it?
With this hypothesis, don't bother with an option.
And it's not yet version 1.0 ;)
What do you think?

**Comment by TiteiKo** [comment]
Hell yeah!
