### ISSUE TITLE
How do I fail the build in CI?

### ISSUE THREAD

**Issue by AndrewVos** [lkdjiin/coco#59]
Firstly, thanks so much for this tool. It is absolutely beautiful.

Secondly, is there any way I can configure coco to output a non-zero exit code when the coverage is below a certain value?

**Comment by lkdjiin** [comment]
Hello @AndrewVos and thank you

I'm afraid there is currently no way to do this. But it sounds like a reasonable feature, and should be easy to add to coco.

Maybe I'll be able to make some tests this weekend, I'll let you know

**Comment by lkdjiin** [comment]
I've a working thing here https://github.com/lkdjiin/coco/tree/exit-on-low-coverage
Just put `:exit_if_low_coverage: true` in your config.
Let me know if it work for you

**Comment by AndrewVos** [comment]
This is awesome! Thanks so much!

One thing that might not work is, for my current project we're reporting coverage on 100%, but would like to fail the build if coverage is below 97%, because we're working to get test coverage up to 100 slowly. Maybe it would be better to have something like `:exit_if_coverage_below: 95`?

Either way, this works for me thanks!

**Comment by lkdjiin** [comment]
I like `:exit_if_coverage_below: 95` much more than `:exit_if_low_coverage: true` ! Thanks for the idea.

I'll update the branch and I'll let you know

**Comment by AndrewVos** [comment]
@lkdjiin That is amazing thanks so much!!

**Comment by lkdjiin** [comment]
It's done here https://github.com/lkdjiin/coco/tree/exit-on-low-coverage
By default the option is `:exit_if_coverage_below: 0` so it's not activated.
Put `:exit_if_coverage_below: 95` in your config and please tell me if it works :smile:

**Comment by AndrewVos** [comment]
Sorry this has taken so long. This is working 100% for me, but he problem now is that the build fails but there's no error message :)

I think this would be really irritating for other people on my team if they don't know about coco

**Comment by lkdjiin** [comment]
Ok ;)
So a big red message «Sadly, the code coverage is below the required value of XX» can be of great use. I'll do it soon

**Comment by lkdjiin** [comment]
There is a message now. I'll merge to master in a couple of days
